# Use an official Python runtime as a parent image
FROM python:3.8.10-slim

# Set the working directory
WORKDIR /app

COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt

